name: scan-image
description: scan and upload image vulnerabilities as SARIF

# NOTE: Fixes "Error: Resource not accessible by integration"
# permissions:
#   contents: read
#   security-events: write

inputs:
  image_tag:
    description: The image tag
    required: true

  fail-build:
    description: Fail the build if vulnerabilities are found
    required: false
    default: "false"

  severity-cutoff:
    description: The minimum severity level to report
    required: false
    default: "high"

  only-fixed:
    description: Only report vulnerabilities that have been fixed
    required: false
    default: "false"

runs:
  using: composite

  steps:
    # SRC: https://github.com/anchore/scan-action/releases/tag/v7.4.2
    - uses: anchore/scan-action@27805bf3b4e84b4a5c980df22ed233c00390a439
      name: Scan ${{ inputs.image_tag }}
      id: scan
      with:
        image: ${{ inputs.image_tag }}
        fail-build: ${{ inputs.fail-build }}
        severity-cutoff: ${{ inputs.severity-cutoff }}
        only-fixed: ${{ inputs.only-fixed == 'true' }}
        output-format: sarif

    # TODO? split into sarif-upload action?
    # SRC: https://github.com/github/codeql-action/releases/tag/v4.37.9
    - uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938
      name: Upload SARIF
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
