name: Semantic Pull-Request
description: Ensures Pull-Requests follow Conventional-Commit standards.

# NOTE: Set in final file
# permissions:
#   pull-requests: read
#
# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

runs:
  using: composite
  steps:
    # SRC: https://github.com/amannn/action-semantic-pull-request
    - uses: amannn/action-semantic-pull-request@v6
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
