name: dependency-review

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    secrets:
      ssh-private-key:
        description: ssh-private-key
        required: false

    inputs:
      # XXX
      ssh-private-key:
        type: string
        description: ssh-private-key
        required: false

      fail-on-severity:
        type: string
        description: fail-on-severity
        required: false
        default: high

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    secrets:
      SSH_KEY_PRIVATE:
        description: ssh-private-key
        required: false

    inputs:
      fail-on-severity:
        type: string
        description: fail-on-severity
        required: false
        default: high

# NOTE: Set in final file as well
permissions:
  contents: read
  # pull-requests: read # TODO? or XXX?

jobs:
  dependency-review:
    name: dependency-review
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE || secrets.ssh-private-key || inputs.ssh-private-key }}

      # TODO? move to actions?
      # SRC: https://github.com/actions/dependency-review-action/releases/tag/v5.0.0
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294
        name: dependency-review
        with:
          fail-on-severity: ${{ inputs.fail-on-severity }}
