name: dependency-review

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      ssh-private-key:
        type: string
        description: ssh-private-key
        required: false

      fail-on-severity:
        type: string
        description: fail-on-severity
        required: false
        default: high

    # TODO?
    # secrets:
    #   SSH_PRIVATE_KEY:
    #     description: ssh-private-key
    #     required: false

  # FIXME when secrets is applied
  # workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# NOTE: Set in final file as well
permissions:
  contents: read
  # pull-requests: read # TODO? or XXX?

jobs:
  dependency-review:
    name: dependency-review
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          # ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # TODO?
          ssh-private-key: ${{ inputs.ssh-private-key }} # XXX?

      # TODO? move to actions?
      - name: dependency-review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: ${{ inputs.fail-on-severity }}
